### PR TITLE
Reapply changes from #141 which were dropped during merging

### PR DESCRIPTION
**Pull request by snorwin**
I think those lines were dropped during a rebase/merge in #141 .

### CODE REVIEW

**Comment by sdalemans** [comment]
Hi snorwin,

I investigated the performance and stability risks of using this library in projects of a large organisation and came across this pull request. I believe this pull request should not end up in a release of the library before some proper defaults are provided for the timeouts of the OkHttp-client. As I see it, the defaults for OkHttp are 10s for connect, read and write timeout. However with this pull request timeouts effectively become 30s connect timeout without any timeout for read, write and call duration (https://github.com/splunk/splunk-library-javalogging/pull/141/files#diff-3aff937fee120b68aadceb636b3fc477ee9b6b924f37fe31408b28797703ec5bR383).

Because these network timeouts are the only way of discarding events, increasing or removing the timeouts is a risk for stability of applications using this library. How about using the current OkHttp client defaults as the defaults for the library?

Not directly related to this pull request, but it might be an idea to warn users for the risks involved when using this library without tuning timeouts and batch sizes.

**Comment by stokpop** [comment]
Hi @snorwin,

is there any change of pulling the timeout settings back into the code base? We now have to create our own jar with this timeout code, and we need that for stability. 

I agree with @sdalemans that sensible defaults should also be implemented with this change, so a suggestion is to set all timeouts on 10 seconds (as per OkHttp). Maybe connect timeout can be made lower (e.g. 1 or 2 seconds), as setting up a connection is expected to be relatively fast. Setting default timeout values to 0 seems risky: seems no timeout is used at all!

(FYI: currently we are running some tests with, in milliseconds, ConnectTimeout=100, CallTimeout=900, ReadTimeout=500 and WriteTimeout=500 and results look promising.)

If there is anything we can do to help, let me know.

**Comment by stokpop** [comment]
Hi @fantavlik, not sure if this is the proper route, but I saw you are able to merge pr's. Can this pr (which seems similar to https://github.com/splunk/splunk-library-javalogging/pull/199) be merged? Possibly also updating the default time-outs as described here? https://github.com/splunk/splunk-library-javalogging/issues/183

**Comment by bparmar-splunk** [comment]
Hi @snorwin / @stokpop,
Modified lines exist in current branch. Please check this [file](https://github.com/splunk/splunk-library-javalogging/blob/main/src/main/java/com/splunk/logging/HttpEventCollectorSender.java#L340).

Since there is no such further changes in this PR, we are closing this PR.

Let us know incase of any queries.

Thank you.

**Pull request closed without merging**
