### PR TITLE
EventHeaderSerializer

### PR DESCRIPTION
**Pull request by snorwin**
Dear Splunk fellows,
For logs that are processed asynchronously or in batches, the time in the log message may differ from the current time (also mentioned #71).  Furthermore, there seems to be a need to easily overwrite the root tags of the JSON event ( #18).  I created the `EventHeaderSerializer` in order to facilitate to set tags (i.e. host, source type, source,  time) based on the message, metadata or on other user logic.

Best Regards,
Norwin

### CODE REVIEW

**Comment by snorwin** [comment]
I verified the `EventHeaderSerialize` manually using log4J . However, I'm still working on fixing the tests. Is there a simple way to run them locally without using Travis?

**Comment by snorwin** [comment]
> I verified the `EventHeaderSerialize` manually using log4J . However, I'm still working on fixing the tests. Is there a simple way to run them locally without using Travis?

Never mind, I managed to run the tests on my machine with the docker image "splunk/splunk".

**Comment by snorwin** [comment]
@shakeelmohamed Is there any chance that this will be reviewed and released soon?

**Comment by shakeelmohamed** [comment]
@snorwin hang tight, one of our developers is working on some changes we hope to release soon. Some of your issues may already be getting resolved from that work

**Comment by hanswurscht** [comment]
Any news on this?  Can we support you in any way?
We would use this to set a different sourcetype for security relevant events directly in our applications.

Thanks!
- Lorenz

**Comment by snorwin** [comment]
Hi @shakeelmohamed 
I have resolved the merge conflicts, could you please check again? I think this feature is really helpful in particular to feed in historical data or facilitate custom logic to set the source type.

Thanks,
Norwin

**Comment by snorwin** [comment]
Same here, I rebased the branch to master due to the artifactory URL change.

@shakeelmohamed is there any chance that this new feature will be included in the next version?

**Comment by shakeelmohamed** [comment]
@snorwin I will see if we can get this prioritized internally. We are even more resource constrained than usual at the moment due to COVID-19. Thank you for your patience

**Comment by fireflo** [comment]
Hello,
Really interested in this feature! We also need to override root-level time (and other parameters)
Thanks!

**Pull request merged**
