### PR TITLE
Fix 100% CPU usage

### PR DESCRIPTION
**Pull request by avdv**
We're seeing constant 100% CPU usage of a single core after rereading the logback config file when using the TcpAppender.

This PR removes the workaround from #9 since that should no longer be necessary because of #43.

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
Thanks for the PR @avdv, do you have any benchmarks that verify this fix?

**Comment by avdv** [comment]
Here's a screenshot to illustrate. You can see at around 9:18:45, I modified logback's config file. From there on, you see a constant 12% CPU usage (my notebook has 8 cores):

shot-2018-10-01_090012
Note that the process is a HTTP service, which is not handling any requests at this time.

We've seen this in production too:
shot-2018-10-01_091527
All services use the same logback config file. After changing the file, all services went up to 100% CPU usage and we had to restart them.

**Comment by shakeelmohamed** [comment]
@avdv thanks, this looks great!
Please fill out the contributing agreement and we'll merge this change: https://www.splunk.com/goto/individualcontributions

**Comment by avdv** [comment]
Hi @shakeelmohamed, I did complete the registration and I am a Splunk contributor now :smiley:

**Comment by shakeelmohamed** [comment]
Thanks @avdv, I'll push to get a release out as soon as possible

**Comment by rm--** [comment]
Hi @shakeelmohamed, may you create a new release including this fix?

**Comment by shakeelmohamed** [comment]
@rm-- yeah, we'll probably get a release out next week

**Comment by shakeelmohamed** [comment]
@avdv yeah we've been swamped internally on some other things, but this is on the top of my personal  to do list. I'm hoping to get it out this week

**Comment by shakeelmohamed** [comment]
@avdv we've just release v1.6.1, thank you agin for your PR

**Comment by avdv** [comment]
Nice, thanks a lot!

**Pull request merged**
