### PR TITLE
Feature/add support for host tag override

### LINKED ISSUE #24: Add support for host tag
Pull request to come.
CLA pending legal review.

### PR DESCRIPTION
**Pull request by afinkenstadt**
Fixes #24

### CODE REVIEW

**Comment by itay** [comment]
Hi @afinkenstadt - any chance you can add a test to verify?

**Comment by afinkenstadt** [comment]
Aside from "it's working in production", I added putative support for sending the "host" metadata through to Splunk event collector:

`curl -Sisk http://ec.splunk.example.com:8088/services/collector/event -H 'Authorization: Splunk 11111111-2222-3333-4444-555555555555' -d '{"event": "{\"level\":\"INFO\",\"msg\":\"hello world #99\"}", "index":"example_test", "host":"host.example.com"}'`
```text
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Date: Tue, 22 Mar 2016 17:37:18 GMT
Server: Splunkd
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Content-Length: 27
Connection: keep-alive
```
```json
{"text":"Success","code":0}
```

**Comment by afinkenstadt** [comment]
CLA signed.

**Comment by shakeelmohamed** [comment]
@afinkenstadt can we close this in favor of #29?

**Pull request closed without merging**
