### PR TITLE
Add connection pool settings and connection request timeout for event posts

### PR DESCRIPTION
**Pull request by jihor**
#### Additions in this PR
This commit adds the following properties to `HttpEventCollectorSender` and consequently, to all the appenders (JUL, Logback and Log4j2): 

Connection pool properties:
- select interval (`pool_select_interval`)
- socket timeout (`pool_socket_timeout`)
- connection timeout (`pool_connection_timeout`)
- max total connections (`pool_max_connections`, only for parallel send mode)

Event's `HttpPost` properties:
- connection request timeout (`connection_request_timeout`)

#### Why is this useful
In the 1.5.3 library version, if Splunk server hangs and HttpPost for one event never completes, JVM will eventually run out of memory, because: 
1) connection has no timeout and, thus, is never failed and reestablished
2) no limit on waiting time is defined for the queued HttpPosts

These are the test results for the logger under moderate load (~400 rps) with emulated Splunk hang:

Current behavior exhibits an OOM error :
selection_055

With the proposed additions, when using `pool_select_interval = 100 msec`, `pool_socket_timeout = 5000 msec`, `pool_connection_timeout = 1000 msec`, `connection_request_timeout = 60000 msec`, the JVM no longer dies with OOM:
selection_056

#### Backward compatibility
For backward compatibility, the default settings of the new values are set identical to the defaults of the Apache HttpClient, so the default behavior will not be changed.

### CODE REVIEW

**Comment by jihor** [comment]
The tests fail because Splunk license has expired in the container used for testing on Travis (splunk/splunk-sdk-travis-ci:6.6-sdk).

I don't think I can fix this on my side.

**Comment by u3r** [comment]
I am experiencing the same problem (OOM).
What can we do to get this merged?

**Comment by hanswurscht** [comment]
Any news on this?

We are currently having some performance issues in our splunk infrastructure. This leads to crashes in our production applications, which send their logs to splunk via hec.
This has a huge impact!

Can this PR be integrated soon?
Should we open a regular splunk case for this?

**Comment by zenmoto** [comment]
This problem should be resolved by the fix merged in #135 and deployed as version 1.8.  If you continue to see similar behavior, please let us know.

**Comment by sachinsharma9393** [comment]
@zenmoto with splunk 1.8.0 , still having high cpu spikes and high heap usage, so analyzed the heap dump, its showing issues with the dispatcher
Screenshot from 2020-05-24 01-04-18

Please help me with this.

**Comment by sachinsharma9393** [comment]
Earlier with splunk 1.5.3 we were facing issues as mentioned in https://github.com/splunk/splunk-library-javalogging/issues/128, so I updated the library to 1.8.0 and analyzed the heap dump because of cpu spikes and continous cpu spikes and gc activity, so the issues are due to dispatcher.
Screenshot from 2020-05-24 01-04-18

**Pull request closed without merging**
