### PR TITLE
Feature/add additional event attributes

### PR DESCRIPTION
**Pull request by afinkenstadt**
In addition to #25 , this pull request adds support for the additional and useful portions of the logger interfaces provided by LogBack, SLF4J, and java. logging. utils:

logger_name
thread_name (or ID)
and the Context maps.

Includes tests to confirm.

### CODE REVIEW

**Comment by joshgarnett** [comment]
+1

**Comment by afinkenstadt** [comment]
Fixes #26

**Comment by afinkenstadt** [comment]
CLA signed.

**Comment by shakeelmohamed** [comment]
@afinkenstadt can we close this in favor of #29?

**Comment by afinkenstadt** [comment]
We can; but merging in #29 will automatically close #28 and #25. :)

**Pull request closed without merging**
